# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1b82319a7c9098e9655c2384a6c3cc5f74f468dd2be460bd9e715e444694b3b2247a5a983f6e37b429a536a1f2110192967883f8b845073d42995ff36fc3c0f

test:
  secret_key_base: d6e39ae947c9da5e9545e8937e4c4695478d87fde0753e720649254dde6623429887dc33203d54decd9991a110e6d93da20c48ec74830b7d9fd8bc3ac30dd3c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
